[package]
name = "xfg"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
description = "eXtensible FrameGraph for `gfx_hal`"
license = "MIT/Apache-2.0"
repository = "https://github.com/omni-viral/xfg-rs.git"

[dependencies]
derivative = "1.0"
gfx-hal = { version = "0.1.0", git = "https://github.com/gfx-rs/gfx.git" }
relevant = "0.1"
smallvec = "0.4"

[dev-dependencies]
gfx_mem = { version = "0.0.0", git = "https://github.com/omni-viral/gfx_mem.git", branch = "impl" }


[[example]]
name = "flat"
path = "examples/flat/flat.rs"
