[package]
name = "xfg-examples"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
repository = "https://github.com/omni-viral/xfg-rs.git"

[dependencies]
cgmath = "0.16"
env_logger = "0.5"
genmesh = "0.5.0"
gfx_mem = { version = "0.1.0", git = "https://github.com/omni-viral/gfx_mem.git", branch = "impl" }
gfx-hal = { version = "0.1.0", git = "https://github.com/gfx-rs/gfx.git" }
gfx-backend-dx12 = { git = "https://github.com/gfx-rs/gfx.git", optional = true }
gfx-backend-gl = { git = "https://github.com/gfx-rs/gfx.git", optional = true }
gfx-backend-metal = { git = "https://github.com/gfx-rs/gfx.git", optional = true }
gfx-backend-vulkan = { git = "https://github.com/gfx-rs/gfx.git", optional = true }
gfx-backend-empty = { git = "https://github.com/gfx-rs/gfx.git", optional = true }
xfg = { path = ".." }
smallvec = "0.4"
winit = "0.10"

[features]
metal = ["gfx-backend-metal"]
gl = ["gfx-backend-gl"]
dx12 = ["gfx-backend-dx12"]
vulkan = ["gfx-backend-vulkan"]

[[bin]]
name = "flat"
path = "src/flat/main.rs"

[[bin]]
name = "pbm"
path = "src/pbm/main.rs"

[[bin]]
name = "pbm_deferred"
path = "src/pbm_deferred/main.rs"